application: shinyfresh
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:

- name: webapp2
  version: latest

handlers:

- url: /static
  static_dir: static
  application_readable: true
  http_headers:
    Cache-Control: public

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon.ico

- url: /dres/.* # GCSs
  script: gcs_wrapper.application

- url: /login # Hand-off
  script: authentication.application

- url: /logout# Hand-off
  script: authentication.application

- url: /files/.*
  script: gcs.application

- url: /.* # Catch-all
  script: main.application

error_handlers:
  - error_code: over_quota
    file: sdtatic/html/gaeoverquota.html